   
version: '3'
services:
  directus:
    container_name: directus
    build: ./directus
    ports:
      - 9001:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/snapshots:/directus/snapshots
      - ./directus/extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: 'e7cc4bd5-0a35-41ab-aa99-3d26215556fd'
      SECRET: 'e60c4413-be96-4b64-bf81-cbfb06da5076'
      TELEMETRY: 'false'
      LOG_LEVEL: 'debug'

      DB_CLIENT: 'pg'
      DB_DATABASE: 'directus-booking'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_USER: 'postgres'
      DB_PASSWORD: 'Test@123'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      EXTENSIONS_AUTO_RELOAD: 'true'
  database:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5100:5432
    networks:
      - directus
    environment:
      POSTGRES_PASSWORD: 'Test@123'
      POSTGRES_DB: 'directus-booking'
networks:
  directus: